const courses = [
  "Курсы для начинающих программистов",
  "Python",
  "Курсы администрирования и программирования 1С",
  "Курсы по разработке мобильных приложений",
  "Курсы СУБД",
  "Oracle",
  "Курсы по тестированию ПО",
  "C (Си), C#, C++",
  "Go",
  ".NET Framework",
  "Разработка компьютерных игр",
  "SQL Server",
  "Разработка СПО в Linux",
  "Курсы программирования на Python, Java, С для школьников",
  "Java",
  "Qt",
  "Курсы веб-программирования: JavaScript, PHP, MySQL и др.",
  "DASA (DevOps)",
  "Postgres Professional",
  "Системный аналитик",
  "Data Science",
];

export default courses;
